### ISSUE TITLE
Set vertx-jooq to use new vert-x reactive clients

### ISSUE THREAD

**Issue by cvgaviao** [jklingsporn/vertx-jooq#125]
The vertx stack is using those: 
 - https://vertx-ci.github.io/vertx-4-preview/docs/vertx-pg-client/java/
- https://vertx-ci.github.io/vertx-4-preview/docs/vertx-mysql-client/java/

Btw, do you already have a branch set to use vertx-core version 4.0.0-SNAPSHOT ?

**Comment by jklingsporn** [comment]
These will be supported in the 5.0 release which I'll put into maven
central next week.

Cristiano Gavião <notifications@github.com> schrieb am Fr., 13. Dez. 2019,
16:54:

**Comment by cvgaviao** [comment]
Hello @jklingsporn ,
I just tried now the version 5.0.0.
Maybe I'm missing something, but the code generated is using `vertx-mysql-postgresql-client-jasync` with `jasync-postgresql` based on kotlin and not `vertx-pg-client`  :(

**Comment by cvgaviao** [comment]
![Screenshot from 2020-02-11 09-32-03](https://user-images.githubusercontent.com/251734/74237071-71c6d580-4cb1-11ea-8f3e-7fd8ef63cd33.png)

**Comment by jklingsporn** [comment]
Can you show me the vertx-jooq-dependencies you are using? The `vertx-jooq-reactive` variants are all using 
```
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-sql-client</artifactId>
            <version>${vertx.version}</version>
        </dependency>
```

**Comment by cvgaviao** [comment]
Yep, my trial was using `vertx-jooq-classic-async`.

I choose it because I'm using Postgresql and my think was that you was about to integrate the new PG reactive driver `vertx-pg-client` that is already using `io.vertx.core.Future<PgConnection>`.

I think you misunderstood my first question above. :)

**Comment by jklingsporn** [comment]
>vertx-pg-client is different from vertx-sql-client
True. If you want to use the reactive client, you need to integrate 
```

**Comment by cvgaviao** [comment]
I'll give it a try.
thanks anyway! :)

**Comment by cvgaviao** [comment]
Hi @jklingsporn, let me do one more question to you. 

I almost finished to generate the vertx pojos of my database. But there are a column of type Point that is not being generated.

Do you think that the [types](https://vertx-ci.github.io/vertx-4-preview/docs/vertx-pg-client/java/#_postgresql_type_mapping) supported by `vertx-pg-client` can be set by your extension programmatically or should I create declarative bindings for them ?

**Comment by rmshven** [comment]
@jklingsporn I am exploring "vertx-jooq-classic-reactive" with "vertx-pg-client". 

The following are the way I am tried to get a DAO object. However, PgPoolOptions, PGClient classes are not present in vertx-jooq or vertx-pg-client jar. Please clarify the approach I am following is correct.

//Setup your jOOQ configuration
Configuration configuration = new DefaultConfiguration();
configuration.set(SQLDialect.POSTGRES);
//no other DB-Configuration necessary because jOOQ is only used to render our statements - not for excecution

//setup Vertx
Vertx vertx = Vertx.vertx();
//setup the client
PgPoolOptions config = new PgPoolOptions().setHost("127.0.0.1").setPort(5432).setUsername("vertx").setDatabase("postgres").setPassword("password");
PgClient client = PgClient.pool(vertx, config);

//instantiate a DAO (which is generated for you)
SomethingDao dao = new SomethingDao(configuration, client);

POM.xml dependencies:
        <dependency>
            <groupId>io.github.jklingsporn</groupId>
            <artifactId>vertx-jooq-classic-reactive</artifactId>
            <version>5.0.1</version>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-pg-client</artifactId>
            <version>4.0.0-milestone5</version>
        </dependency>

**Comment by rmshven** [comment]
@cvgaviao 

Were you able to use jooq-classic with vertx-pg-client? If that's the case, can you clarify my query?
