### ISSUE TITLE
`toJson()` crashes when converting an enum type with a null value

### ISSUE THREAD

**Issue by guss77** [jklingsporn/vertx-jooq#15]
When calling `toJson()` on a Pojo with a nullable enum field (or a just created object), an NPE is thrown from the call to `getLiteral()` on the null value.

Likely introduced by the fix in 6f1a44ba5c5b5330a17b7e2ace162af9a98974a6 to issue #14 .

My workaround was to implement `handleCustomTypeToJson()` like this:

```
@Override
protected boolean handleCustomTypeToJson(TypedElementDefinition<?> column, String getter, String columnType, String javaMemberName, JavaWriter out) {
    if(column.getDatabase().getEnum(column.getSchema(), column.getType().getUserType()) != null) { // isEnum() from AbstractVertxGenerator
        out.ref("org.jooq.EnumType");
        out.ref("java.util.Optional");
        out.tab(2).println("json.put(\"%s\",Optional.ofNullable(%s()).map(EnumType::getLiteral).orElse(null));", javaMemberName, getter);
        return true;
    }
    return false;
}
```

I can offer this as a patch to the the `AbstractVertxGenerator` if you want.

**Comment by jklingsporn** [comment]
Unfortunately I cannot provide a test for this as HSQLDB doesn't have enums. Even it vertx-jooq-async, which uses MySQL, it is currently not possible to provide a test-case because there is a bug when generating enums using jOOQ with MySQL.
Anyways, thanks for the report. Bug is fixed an version 2.3.3 with a fix about to be deployed.
