### ISSUE TITLE
MariaDB support for lastInsertId

### ISSUE THREAD

**Issue by leavestyle-jia** [jklingsporn/vertx-jooq#173]
change to classic-reactive, call `dao.insertReturningPrimary(obj)` will throw UnsupportedOperationException().

I'm confused for that.

<img width="631" alt="屏幕快照 2021-01-06 下午3 03 51" src="https://user-images.githubusercontent.com/25811040/103739586-c8a76d00-5030-11eb-82ea-97b4f8008695.png">
<img width="1069" alt="屏幕快照 2021-01-06 下午3 05 18" src="https://user-images.githubusercontent.com/25811040/103739550-bf1e0500-5030-11eb-99be-4ac1701dab6f.png">

**Comment by jklingsporn** [comment]
Hello,
can you please tell me more about your configuration? The method should be overridden by the code generator in the actual DAO-implementations (see [this generated DAO](https://github.com/jklingsporn/vertx-jooq/blob/master/vertx-jooq-generate/src/test/java/generated/classic/reactive/mysql/tables/daos/SomethingDao.java#L175) from the tests). However this only happens if the configured dialect for code generation is Mysql. 
This is the relevant part in the [code generator](https://github.com/jklingsporn/vertx-jooq/blob/510f38f920a585e5c4745f3441283a28a1d49a1f/vertx-jooq-generate/src/main/java/io/github/jklingsporn/vertx/jooq/generate/builder/VertxGeneratorBuilder.java#L276-L282):
```
if (schema.getDatabase().getDialect().family().equals(SQLDialect.MYSQL)) {
                    out.println();
                    out.tab(1).override();
                    out.tab(1).println("protected java.util.function.Function<io.vertx.sqlclient.RowSet<io.vertx.sqlclient.Row>,Long> extractMysqlLastInsertProperty(){");
                    out.tab(2).println("return rs -> rs.property(io.vertx.mysqlclient.MySQLClient.LAST_INSERTED_ID);");
                    out.tab(1).println("}");
                }
```

**Comment by LeaSty** [comment]
My db is mariadb, so how can I fix that?

**Comment by jklingsporn** [comment]
For now you would need to fork the generate-module and change the `VertxGeneratorBuilder` like this:
```
if (schema.getDatabase().getDialect().family().equals(SQLDialect.MYSQL) || schema.getDatabase().getDialect().family().equals(SQLDialect.MARIADB)) {
                    out.println();
                    out.tab(1).override();
                    out.tab(1).println("protected java.util.function.Function<io.vertx.sqlclient.RowSet<io.vertx.sqlclient.Row>,Long> extractMysqlLastInsertProperty(){");
                    out.tab(2).println("return rs -> rs.property(io.vertx.mysqlclient.MySQLClient.LAST_INSERTED_ID);");
                    out.tab(1).println("}");
                }
```
Or wait until I've implemented it.

**Comment by LeaSty** [comment]
I can wait 6.1.0 to use that😁

**Comment by jklingsporn** [comment]
Should be available on maven central.

**Comment by leavestyle-jia** [comment]
Nice, It worked. 👏👏👏

**Comment by leavestyle-jia** [comment]
When will 6.1.0 be released ? Handsome man 😅

**Comment by jklingsporn** [comment]
Should be available at maven central.

leavestyle <notifications@github.com> schrieb am Do., 7. Jan. 2021, 07:30:
